import "./globals.css";
import { Albert_Sans } from "next/font/google";
import { ApolloWrapper } from "@/components/ApolloClientWrapper";
import { ClerkProvider } from "@clerk/nextjs";

const albert = Albert_Sans({
  subsets: ["latin"],
  weight: ["200", "500", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={albert.className}>
          <ApolloWrapper>{children}</ApolloWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
